name: Deploy

env:
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}
  GCLOUD_PROJECT: joshlong
  GH_TOKEN: ${{ secrets.MOGUL_GITHUB_PACKAGES_PERSONAL_ACCESS_TOKEN }}
  GH_USER: ${{ github.actor }}
  APP_NAME: gateway

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: bootiful-media-mogul/github-actions-setup-jvm-build-env@main
        with:
          gh_token: ${{ env.GH_TOKEN }}
          gh_user: ${{ env.GH_USER }}

      - run: ./mvnw --batch-mode --no-transfer-progress -DskipTests -Pnative native:compile

      - uses: bootiful-media-mogul/github-actions-setup-container-build-env@main
        with:
          gh_token: ${{ env.GH_TOKEN }}
          app_name: ${{ env.APP_NAME }}
          gcloud_sa_key: '${{ secrets.GCLOUD_SA_KEY }}'
          gcloud_project: ${{ env.GCLOUD_PROJECT }}
